# Generated by Django 4.0.5 on 2022-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerais',
            name='evento',
            field=models.CharField(blank=True, choices=[('Assembleia', 'Assembleia'), ('Congresso', 'Congresso')], max_length=30, null=True),
        ),
    ]
