# Generated by Django 4.0.5 on 2023-04-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_assembleia',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.usuarios'),
        ),
    ]
