# Generated by Django 4.0.5 on 2023-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_alter_usuarios_assembleia_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_assembleia',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
