# Generated by Django 4.0.5 on 2022-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_gerais_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerais',
            name='assistente',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gerais',
            name='coordenador',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
