# Generated by Django 4.0.5 on 2023-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_usuarios_assembleia_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerais_Congresso_Sexta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregação', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.CharField(blank=True, max_length=60, null=True)),
                ('data_do_evento', models.DateField(blank=True, null=True)),
                ('valor_da_passagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coordenador', models.CharField(blank=True, max_length=60, null=True)),
                ('assistente', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_Congresso_Sexta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('identidade', models.BigIntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('observações', models.CharField(blank=True, max_length=200, null=True)),
                ('adquiriu', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=30, null=True, verbose_name='Solicitou Passagem?')),
                ('quitado', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=30, null=True, verbose_name='Quitado?')),
                ('poltrona', models.IntegerField(blank=True, null=True)),
                ('carro', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('Outra Congregação', 'Outra Congregação')], max_length=30, null=True)),
            ],
        ),
    ]
